const Data = [
    {
        id: '1',
        name: 'Text Summarize',
        description: 'Summarize any text, exactly how you need it.',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'TEXT',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '2',
        name: 'Language Translation',
        description: 'Language translation using LLM Chain with a Chat Prompt Template and Chat Model',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '3',
        name: 'Text to Takeaways',
        description: 'Pull out key takeaways and quotes from any text, long or short',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'TEXT',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '4',
        name: 'SQL insight Generate',
        description: 'Generate written insights from any SQL query',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'DATA',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '5',
        name: 'Sentiment Analyze',
        description: 'Assess the sentiment of any text as positive or negative',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'TEXT',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '6',
        name: 'SQL Optimize',
        description: 'Improve the performance of a SQL query',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'DATA',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '7',
        name: 'Talk to PDF',
        description: 'No-Code - Talk to Your PDF Files',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'TEXT',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '8',
        name: 'QnA Retrieval Chain',
        description: 'Github repo QnA using conversational retrieval QA chain',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '9',
        name: 'Question Suggest',
        description: 'Suggest questions you can answer with a database table',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'DATA',
        subCategory: null,
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '10',
        name: 'Knowdy',
        description: 'An Intelligent Gen AI assistant like ChatGPT',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'KMS',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '11',
        name: 'MediQA ',
        description: 'Generating insights for doctor-patient discussions and understanding',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'HEALTH',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '12',
        name: 'Report Insight Semantic',
        description: 'Keyword search on your own documents to semantic search',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'REPORTS',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '13',
        name: 'Query Bot',
        description: 'Intelligent responses to your queries, instantly and accurately',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'SUPPORT',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '14',
        name: 'TableQA',
        description: 'Generate and Refine SQL query using natural language',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'DATABASE',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '15',
        name: 'BFSI Document Extract',
        description: 'Automate the extraction of relevant information from the documents',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'BFSI',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    },
    {
        id: '16',
        name: 'TELECOM FAQ ',
        description: 'FAQ documents and semantic similarity search to answer new incoming questions',
        apikeyid: null,
        deployed: false,
        flowData: '',
        category: 'CUSTOM',
        subCategory: 'TELCO',
        image: '',
        createdDate: '2023-06-09T08:42:55+0000',
        updatedDate: '2023-06-09T08:42:55+0000'
    }
]
export default Data
